// +build !ignore_autogenerated

// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2020-2021 Intel Corporation

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *N5010Cluster) DeepCopyInto(out *N5010Cluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new N5010Cluster.
func (in *N5010Cluster) DeepCopy() *N5010Cluster {
	if in == nil {
		return nil
	}
	out := new(N5010Cluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *N5010Cluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *N5010ClusterList) DeepCopyInto(out *N5010ClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]N5010Cluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new N5010ClusterList.
func (in *N5010ClusterList) DeepCopy() *N5010ClusterList {
	if in == nil {
		return nil
	}
	out := new(N5010ClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *N5010ClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *N5010ClusterNode) DeepCopyInto(out *N5010ClusterNode) {
	*out = *in
	if in.FPGA != nil {
		in, out := &in.FPGA, &out.FPGA
		*out = make([]N5010Fpga, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new N5010ClusterNode.
func (in *N5010ClusterNode) DeepCopy() *N5010ClusterNode {
	if in == nil {
		return nil
	}
	out := new(N5010ClusterNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *N5010ClusterSpec) DeepCopyInto(out *N5010ClusterSpec) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]N5010ClusterNode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new N5010ClusterSpec.
func (in *N5010ClusterSpec) DeepCopy() *N5010ClusterSpec {
	if in == nil {
		return nil
	}
	out := new(N5010ClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *N5010ClusterStatus) DeepCopyInto(out *N5010ClusterStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new N5010ClusterStatus.
func (in *N5010ClusterStatus) DeepCopy() *N5010ClusterStatus {
	if in == nil {
		return nil
	}
	out := new(N5010ClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *N5010Fpga) DeepCopyInto(out *N5010Fpga) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new N5010Fpga.
func (in *N5010Fpga) DeepCopy() *N5010Fpga {
	if in == nil {
		return nil
	}
	out := new(N5010Fpga)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *N5010FpgaStatus) DeepCopyInto(out *N5010FpgaStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new N5010FpgaStatus.
func (in *N5010FpgaStatus) DeepCopy() *N5010FpgaStatus {
	if in == nil {
		return nil
	}
	out := new(N5010FpgaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *N5010Node) DeepCopyInto(out *N5010Node) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new N5010Node.
func (in *N5010Node) DeepCopy() *N5010Node {
	if in == nil {
		return nil
	}
	out := new(N5010Node)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *N5010Node) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *N5010NodeList) DeepCopyInto(out *N5010NodeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]N5010Node, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new N5010NodeList.
func (in *N5010NodeList) DeepCopy() *N5010NodeList {
	if in == nil {
		return nil
	}
	out := new(N5010NodeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *N5010NodeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *N5010NodeSpec) DeepCopyInto(out *N5010NodeSpec) {
	*out = *in
	if in.FPGA != nil {
		in, out := &in.FPGA, &out.FPGA
		*out = make([]N5010Fpga, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new N5010NodeSpec.
func (in *N5010NodeSpec) DeepCopy() *N5010NodeSpec {
	if in == nil {
		return nil
	}
	out := new(N5010NodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *N5010NodeStatus) DeepCopyInto(out *N5010NodeStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FPGA != nil {
		in, out := &in.FPGA, &out.FPGA
		*out = make([]N5010FpgaStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new N5010NodeStatus.
func (in *N5010NodeStatus) DeepCopy() *N5010NodeStatus {
	if in == nil {
		return nil
	}
	out := new(N5010NodeStatus)
	in.DeepCopyInto(out)
	return out
}
