# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

# permissions for end users to view n3000clusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: n3000cluster-viewer-role
rules:
- apiGroups:
  - fpga.intel.com
  resources:
  - n3000clusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fpga.intel.com
  resources:
  - n3000clusters/status
  verbs:
  - get
